import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { corsHeaders, handlePreflightRequest } from "../_utils/cors.ts";

/**
 * Enhanced Video Generation with Multiple Providers
 * 
 * Priority:
 * 1. Pollinations.ai (FREE video generation)
 * 2. Runway ML (requires API key)
 * 3. Pika (if configured)
 */

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return handlePreflightRequest();
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      throw new Error("Missing authorization header");
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const token = authHeader.replace("Bearer ", "");
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser(token);

    if (authError || !user) {
      throw new Error("Unauthorized");
    }

    const body = await req.json();
    const {
      prompt,
      duration = 5,
      quality = "standard",
      provider = "auto",
    } = body;

    if (!prompt) {
      throw new Error("Prompt is required");
    }

    console.log("🎬 [Video Gen] Request:", { userId: user.id, prompt, duration, provider });

    let videoUrl: string | null = null;
    let usedProvider = "";
    let cost = 0;

    // ============================================
    // PROVIDER 1: POLLINATIONS.AI VIDEO (FREE)
    // ============================================
    if (provider === "auto" || provider === "pollinations") {
      try {
        console.log("🌸 Trying Pollinations.ai video...");

        // Pollinations.ai video API
        const pollinationsVideoUrl = "https://text.pollinations.ai/video";
        const videoPromptPayload = {
          prompt: prompt,
          duration: Math.min(duration, 10), // Max 10 seconds for free tier
          resolution: "720p",
        };

        const pollinationsResponse = await fetch(pollinationsVideoUrl, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(videoPromptPayload),
        });

        if (pollinationsResponse.ok) {
          const data = await pollinationsResponse.json();
          videoUrl = data.video_url || data.url;
          usedProvider = "Pollinations.ai";
          cost = 0;
          console.log("✅ [Video Gen] Pollinations.ai SUCCESS");
        } else {
          console.warn("⚠️ Pollinations video failed:", await pollinationsResponse.text());
        }
      } catch (error) {
        console.warn("⚠️ Pollinations video error:", error);
      }
    }

    // ============================================
    // PROVIDER 2: RUNWAY ML (requires API key)
    // ============================================
    if (!videoUrl && (provider === "auto" || provider === "runway")) {
      try {
        console.log("🎬 Trying Runway ML...");

        const { data: runwayConfig } = await supabase
          .from("GlobalAiConnection")
          .select("apiKey, baseUrl")
          .eq("provider", "RUNWAY")
          .eq("isActive", true)
          .single();

        if (runwayConfig?.apiKey) {
          const baseUrl = runwayConfig.baseUrl || "https://api.runwayml.com/v1";
          const runwayResponse = await fetch(`${baseUrl}/video/generate`, {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${runwayConfig.apiKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              prompt: prompt,
              duration: duration,
              fps: 24,
              width: 1280,
              height: 720,
            }),
          });

          if (runwayResponse.ok) {
            const data = await runwayResponse.json();
            videoUrl = data.video_url;
            usedProvider = "Runway ML";
            cost = duration * 0.20; // $0.20 per second
            console.log("✅ [Video Gen] Runway SUCCESS");
          }
        } else {
          console.log("ℹ️ Runway not configured, skipping");
        }
      } catch (error) {
        console.warn("⚠️ Runway error:", error);
      }
    }

    // ============================================
    // FALLBACK: Generate placeholder video
    // ============================================
    if (!videoUrl) {
      console.log("⚠️ All video providers failed, using placeholder");

      // Create a simple text-to-video placeholder using image sequence
      const encodedPrompt = encodeURIComponent(`Video: ${prompt} (Generated by AI)`);
      videoUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=1280&height=720&nologo=true`;
      usedProvider = "Placeholder (Static Image)";
      cost = 0;

      return new Response(
        JSON.stringify({
          success: false,
          error: "Video generation not available",
          suggestion: {
            message: "Configure Runway ML API key for real video generation",
            alternatives: [
              "Use image generation instead",
              "Configure Runway ML in Super Admin",
              "Use external video generation tools",
            ],
          },
          placeholder: {
            url: videoUrl,
            note: "This is a static image placeholder, not a video",
          },
        }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // ============================================
    // UPLOAD TO SUPABASE STORAGE (if external URL)
    // ============================================
    let finalUrl = videoUrl;

    if (usedProvider !== "Placeholder (Static Image)") {
      try {
        const videoResponse = await fetch(videoUrl);
        const videoBlob = await videoResponse.blob();
        const videoBuffer = await videoBlob.arrayBuffer();

        const fileName = `videos/${user.id}/${Date.now()}-${crypto.randomUUID()}.mp4`;
        const { error: uploadError } = await supabase.storage
          .from("media-generations")
          .upload(fileName, videoBuffer, {
            contentType: "video/mp4",
            upsert: false,
          });

        if (!uploadError) {
          const { data: { publicUrl } } = supabase.storage
            .from("media-generations")
            .getPublicUrl(fileName);
          finalUrl = publicUrl;
        }
      } catch (uploadError) {
        console.warn("⚠️ Upload failed, using external URL:", uploadError);
      }
    }

    // ============================================
    // SAVE TO DATABASE
    // ============================================
    try {
      await supabase.from("MediaGeneration").insert({
        userId: user.id,
        type: "VIDEO",
        provider: usedProvider,
        prompt: prompt,
        url: finalUrl,
        duration: duration,
        quality: quality,
        cost: cost,
        status: "COMPLETED",
        metadata: {
          originalUrl: videoUrl,
          provider: usedProvider,
        },
      });
    } catch (dbError) {
      console.warn("⚠️ DB insert failed:", dbError);
    }

    // ============================================
    // SUCCESS RESPONSE
    // ============================================
    return new Response(
      JSON.stringify({
        success: true,
        video: {
          url: finalUrl,
          prompt: prompt,
          duration: duration,
          quality: quality,
          provider: usedProvider,
          cost: cost,
          free: cost === 0,
        },
        message: `Vídeo gerado com ${usedProvider}!`,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error: any) {
    console.error("❌ [Video Gen] Error:", error);

    return new Response(
      JSON.stringify({
        error: error.message || "Unknown error",
        details: error.stack,
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
